### ISSUE TITLE
Is anything here outdated?

### ISSUE THREAD

**Issue by HeavyWeaponsPie** [Glubbable/Slender-Fortress-Documentation#2]
Because if people are still going to use this, then they may be missing out on infomation.

**Comment by Kenzzer** [comment]
Slender Fortress is archived, as such this repo is no longer meant to be used. Please refer to Slender Fortress modified repository.

**Comment by HeavyWeaponsPie** [comment]
No I mean, Glubbable's servers.

**Comment by Kenzzer** [comment]
Those servers no longer exist, they still appear in server browser but they no longer belong to the group. They also use a private version, and don't accept outsider contribution.

**Comment by HeavyWeaponsPie** [comment]
Huh? They don't own the server anymore? What happened? I guess this may have to do with Glubbable basically quiting SF2 and becoming a VTuber, basically abandoning TF2 entirely.

**Comment by Kenzzer** [comment]
I don't see how such comments belong to this repository nor to your original issue.
